### ISSUE TITLE
scan operator may run multiple times with multiple listeners

### ISSUE THREAD

**Issue by musicq** [ReactiveX/rxdart#304] opened 2019-07-23 06:39 UTC
Reproduce code

```dart
import 'package:rxdart/rxdart.dart';

main() {
  final t = BehaviorSubject.seeded(0);
  final p = t.scan((acc, cur, _) => acc + cur, 0);

  p.listen((t) => print('xxxxx is $t'));
  p.listen((t) => print('ooooo is $t'));

  t.add(1);
}
```

Result

```plaintext
xxxxx is 0
ooooo is 0
xxxxx is 1
ooooo is 2
```

Expect

```plaintext
xxxxx is 0
ooooo is 0
xxxxx is 1
ooooo is 1
```

I think the callback in `scan` should only run once when the source stream emits. But it seems to run twice.

I've searched the same problem in StackOverflow.

https://stackoverflow.com/q/54485361/6733917

**Comment by frankpepermans** [comment] 2019-07-23 07:57
Seems that scan is using a `StreamTransformer.fromHandlers`, whereas we normally create a new inner `StreamController` instead.

This PR now implements our standard transformer https://github.com/ReactiveX/rxdart/pull/305

Looks like the issue is fixed with this change.

**Closed** 2019-07-23 08:03 UTC
